version: 1

checkmarx: 
  scan:
    #optional
    tags:
       "fromConfig": "true"

    project:
      tags: 
        "fromConfig": "true"

    configs:
      sast:
        presetName: 'High and Medium'
        incremental: 'false'
